/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.urielsda;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author urielwenceslao
 */
public class SDAHymnal extends javax.swing.JFrame {

    /**
     * Creates new form SDAHymnal
     */
    
    private String dir = System.getProperty("user.dir");
    private String fullpath = dir + "/sources/lyrics/MasterList.csv"; // this is to be modified on netbeans
    DefaultTableModel model;
    TableRowSorter<DefaultTableModel> tableSorter;
    DefaultTableModel SortedTable;
    
    public SDAHymnal() {
        initComponents();
        populate();        
}
   // populate table
    
   private void populate()
   {
   try {                                         

            model = (DefaultTableModel) jSonglist.getModel();
            String[] splitFileStr = null;
            BufferedReader br = null;     
            try {
                br = new BufferedReader(new FileReader(fullpath));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(SDAHymnal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            String st;
            int index = 0;
            try {
                while ((st = br.readLine()) != null) {
                    splitFileStr = st.split(",");
                    model.addRow(new Object[]{splitFileStr[index],splitFileStr[index+1]});
                  }
            }catch (Exception e){}
            br.close(); 
        } catch (IOException ex) {
            Logger.getLogger(SDAHymnal.class.getName()).log(Level.SEVERE, null, ex);
        }
            
   
   }
   //Filter data
    private void filter (String query)
    {
        
        tableSorter = new TableRowSorter<DefaultTableModel>(model);
        jSonglist.setRowSorter(tableSorter);
        tableSorter.setRowFilter(RowFilter.regexFilter(query));
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jSonglist = new javax.swing.JTable();
        SearchValue = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSonglist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hymn Number", "Title"
            }
        ));
        jSonglist.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSonglist, org.jdesktop.beansbinding.ELProperty.create("${selectedElement}"), jSonglist, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        jSonglist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSonglistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jSonglist);

        SearchValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchValueActionPerformed(evt);
            }
        });
        SearchValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchValueKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Search Hymn Number/Title: ");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        jLabel2.setText("by: Uriel Wenceslao");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(SearchValue, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchValue, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchValueActionPerformed

    private void jSonglistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSonglistMouseClicked
        LyricsPanel lyrics = new LyricsPanel();
        /*
        int row = jSonglist.rowAtPoint(evt.getPoint());
        int col = jSonglist.columnAtPoint(evt.getPoint());
        Object songFilename = model.getDataVector().get(row);
         String[] lyricsFname = songFilename.toString().split(",");
         */
        int row = jSonglist.getSelectedRow();
        //lyrics.recievedHymnalValue = replaceChar(lyricsFname[0])+ "-" +replaceChar(lyricsFname[1]);
        lyrics.recievedHymnalValue = jSonglist.getValueAt(row,0)+ "-" + jSonglist.getValueAt(row,1);
        lyrics.start();
  
    }//GEN-LAST:event_jSonglistMouseClicked

    private void SearchValueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchValueKeyReleased
        String query = SearchValue.getText();
        filter(query);
        
    }//GEN-LAST:event_SearchValueKeyReleased

    String replaceChar(String origCharter) {
	String a = origCharter.toString();
	String str2 = a.replaceAll("\\[","");
	String str3 = str2.replaceAll("]","");
	return str3;
}
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SDAHymnal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SDAHymnal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SDAHymnal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SDAHymnal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SDAHymnal().setVisible(true);
            }
        });
  } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SearchValue;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jSonglist;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
